priority_rules:
  - name: hotfix
    priority: 3000
    conditions:
      - label = hotfix
    allow_checks_interruption: true

  - name: dependencies
    priority: 500
    conditions:
      - author ~= ^(renovate|dependabot|doxynix-deps-bot)\[bot\]$

queue_rules:
  - name: default
    update_method: rebase
    queue_conditions:
      - "#check-pending = 0"
      - "#check-failure = 0"
      - -conflict
      - -draft
      - "-title ~= (?i)(wip|draft|🚧)"
      - or:
          - author ~= ^(renovate|dependabot|doxynix-(release|deps)-bot)\[bot\]$
          - approved-reviews-by = coderabbitai[bot]
    merge_conditions:
      - "#check-pending = 0"
      - "#check-failure = 0"
      - or:
          - author ~= ^(renovate|dependabot|doxynix-(release|deps)-bot)\[bot\]$
          - approved-reviews-by = coderabbitai[bot]
    merge_method: squash
    commit_message_format:
      title: pr-title
      body: pr-body

pull_request_rules:
  - name: label hotfixes automatically
    conditions:
      - head ~= ^hotfix/
    actions:
      label:
        add: ["hotfix"]

  - name: automatic merge for Kramarich0
    conditions:
      - author = Kramarich0
      - approved-reviews-by = coderabbitai[bot]
      - -draft
      - -conflict
      - "#check-pending = 0"
      - "#check-failure = 0"
      - "-title ~= (?i)(wip|draft|🚧)"
    actions:
      queue:
        name: default
      comment:
        message: "@Kramarich0! All CI and type checks for SIEM have passed. Entering the merge queue! 🚀"

  - name: automatic merge for release-please
    conditions:
      - author = doxynix-release-bot[bot]
      - -draft
      - -conflict
      - "#check-pending = 0"
      - "#check-failure = 0"
    actions:
      queue:
        name: default

  - name: automatic merge for dependencies
    conditions:
      - or:
          - author = renovate[bot]
          - author = dependabot[bot]
          - author = doxynix-deps-bot[bot]
      - -draft
      - -conflict
      - "#check-pending = 0"
      - "#check-failure = 0"
      - -label = "major-update"
    actions:
      queue:
        name: default
      comment:
        message: "@Kramarich0! Dependencies updated and verified. 📦"

  - name: label on conflicts
    conditions:
      - conflict
      - -closed
    actions:
      label:
        add: ["conflict"]
      comment:
        message: "Oops, @Kramarich0, there is a merge conflict in SIEM. Please resolve it manually! 🛠️"

merge_protections_settings:
  reporting_method: check-runs