name: Apply Production Database Migrations

on:
  push:
    branches:
      - main

jobs:
  migrate:
    name: Drizzle Database Migrate
    runs-on: ubuntu-latest

    steps:
      - name: ⬇Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Install Doppler CLI
        uses: DopplerHQ/cli-action@4819d808ab99e5cde19a0637a16536a4038fad73

      - name: Run Drizzle Migrations
        run: doppler run -- bun run db:migrate
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
